### ISSUE TITLE
Release 1.1.1?

### ISSUE THREAD

**Issue by moiristo** [ydkn/capistrano-git-copy#21]
I'm suffering from the missing 'local repo mirror' problem, could you please create a new release?

**Comment by moiristo** [comment]
Upon closer inspection, better wait :) I just tried to deploy by bundling with master, but an error occurs. Fyi, here's the cap output:

``` ruby
INFO [f95f8dbf] Running /usr/bin/env git ls-remote --heads git@git.user.nl:railsapp.git as user@localhost
INFO [f95f8dbf] Finished in 0.839 seconds with exit status 0 (successful).
INFO [b137b403] Running /usr/bin/env mkdir -p /apps/railsapp /apps/railsapp/rails/releases as user@example.com
INFO [b137b403] Finished in 0.604 seconds with exit status 0 (successful).
INFO [30d82c44] Running /usr/bin/env mkdir -p /apps/railsapp/log /apps/railsapp/tmp as user@example.com
INFO [30d82c44] Finished in 0.021 seconds with exit status 0 (successful).
INFO [e0e999b4] Running /usr/bin/env mkdir -p /apps/railsapp/config as user@example.com
INFO [e0e999b4] Finished in 0.020 seconds with exit status 0 (successful).
INFO [b41647c8] Running /usr/bin/env mkdir -p /apps/railsapp/data/public/assets as user@example.com
INFO [b41647c8] Finished in 0.023 seconds with exit status 0 (successful).
INFO [b63d3570] Running /usr/bin/env rm -rf /private/var/folders/9n/r_5dl3bj4lnb3yf0dnjlwyd00000gq/T/railsapp_production_d5e656a0_ff9fc616/repo as user@localhost
INFO [b63d3570] Finished in 0.030 seconds with exit status 0 (successful).
INFO [751abe97] Running /usr/bin/env mkdir -p /private/var/folders/9n/r_5dl3bj4lnb3yf0dnjlwyd00000gq/T/railsapp_production_d5e656a0_ff9fc616 as user@localhost
INFO [751abe97] Finished in 0.011 seconds with exit status 0 (successful).
INFO [c550d78f] Running /usr/bin/env git clone git@git.user.nl:railsapp.git /private/var/folders/9n/r_5dl3bj4lnb3yf0dnjlwyd00000gq/T/railsapp_production_d5e656a0_ff9fc616/repo as user@localhost
INFO [c550d78f] Finished in 16.617 seconds with exit status 0 (successful).
INFO [f53aee10] Running /usr/bin/env git remote update as user@localhost
INFO [f53aee10] Finished in 0.353 seconds with exit status 0 (successful).
INFO [ea8698a2] Running /usr/bin/env git reset --hard ce165a82cbda2071670183d48ae8689ffc090fac as user@localhost
INFO [ea8698a2] Finished in 0.046 seconds with exit status 0 (successful).
INFO [bf987f90] Running /usr/bin/env git submodule init as user@localhost
INFO [bf987f90] Finished in 0.101 seconds with exit status 0 (successful).
INFO [ff957ee6] Running /usr/bin/env git submodule update as user@localhost
INFO [ff957ee6] Finished in 0.069 seconds with exit status 0 (successful).
INFO [a8047191] Running /usr/bin/env git submodule foreach --recursive git submodule update --init as user@localhost
INFO [a8047191] Finished in 0.079 seconds with exit status 0 (successful).
INFO [6c120119] Running /usr/bin/env git clean -d -f as user@localhost
INFO [6c120119] Finished in 0.010 seconds with exit status 0 (successful).
INFO [3a263575] Running /usr/bin/env git submodule foreach --recursive git clean -d -f as user@localhost
INFO [3a263575] Finished in 0.075 seconds with exit status 0 (successful).
INFO [c01097be] Running /usr/bin/env /Users/user/.rvm/gems/ruby-2.2.2@rails/bundler/gems/capistrano-git-copy-f5c344881d01/vendor/git-archive-all/git-archive-all --prefix='' /private/var/folders/9n/r_5dl3bj4lnb3yf0dnjlwyd00000gq/T/railsapp_production_d5e656a0_ff9fc616/archive.tar.gz as user@localhost
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Command::Failed: /Users/user/.rvm/gems/ruby-2.2.2@rails/bundler/gems/capistrano-git-copy-f5c344881d01/vendor/git-archive-all/git-archive-all exit status: 32512
/Users/user/.rvm/gems/ruby-2.2.2@rails/bundler/gems/capistrano-git-copy-f5c344881d01/vendor/git-archive-all/git-archive-all stdout: Nothing written
/Users/user/.rvm/gems/ruby-2.2.2@rails/bundler/gems/capistrano-git-copy-f5c344881d01/vendor/git-archive-all/git-archive-all stderr: env: /Users/user/.rvm/gems/ruby-2.2.2@rails/bundler/gems/capistrano-git-copy-f5c344881d01/vendor/git-archive-all/git-archive-all: No such file or directory

Tasks: TOP => git_copy:create_release
(See full trace by running task with --trace)
The deploy has failed with an error: /Users/user/.rvm/gems/ruby-2.2.2@rails/bundler/gems/capistrano-git-copy-f5c344881d01/vendor/git-archive-all/git-archive-all exit status: 32512
/Users/user/.rvm/gems/ruby-2.2.2@rails/bundler/gems/capistrano-git-copy-f5c344881d01/vendor/git-archive-all/git-archive-all stdout: Nothing written
/Users/user/.rvm/gems/ruby-2.2.2@rails/bundler/gems/capistrano-git-copy-f5c344881d01/vendor/git-archive-all/git-archive-all stderr: env: /Users/user/.rvm/gems/ruby-2.2.2@rails/bundler/gems/capistrano-git-copy-f5c344881d01/vendor/git-archive-all/git-archive-all: No such file or directory
```

**Comment by ydkn** [comment]
Hi,

this problem occurs because git-archive-all is a submodule and referencing the gem through git/github won't clone the submodule.

Simply update the submodule:
```
cd /Users/user/.rvm/gems/ruby-2.2.2@rails/bundler/gems/capistrano-git-copy-f5c344881d01
git submodule init
git submodule update
```
If your are updating to another revision you have to do this again.

But I'm not sure what you mean with 'local repo mirror problem'... can you please give me a few more details on the problem?

**Comment by moiristo** [comment]
I see, will try that this monday. The thing is, sometimes the local repo checkout (e.g. /private/var/folders/9n/r_5dl3bj4lnb3yf0dnjlwyd00000gq/T/railsapp_production_d5e656a0_ff9fc616/repo) is missing the '.git' folder. I don't know if OSX (10.11.2) is doing this or something else, but the result is that the deploy fails because the checkout in /repo is not a git repo anymore. I think commit 6c53de02f585aebc0519d32e5d91ad693559e9d8 should fix that.

**Comment by ydkn** [comment]
You are complete right about that. I had the same problem (I still don't know why) so I added the check.

I was waiting for #18 to make a 1.2.0 release. But since I'm waiting for feedback quite a while know I'm going to release it anyway.

Let me know if using the current master works on your system so I can make the release.

**Comment by moiristo** [comment]
Just checked this by removing the .git folder manually and then trying to deploy using the version in master. Works fine! :shipit:

**Comment by ydkn** [comment]
Thanks for your feedback. Just release v1.2.0
